name: ATMI-PlusMinus-Deploy

on:
  pull_request:
    branches:
      - main
  
  push:
    branches:
      - main
      - Laravel-CI/CD


jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
        -   uses: actions/checkout@v3

        -   name: Compile CSS and Javascript
            run: |
                npm install
                npm run build

        -   name: Install PHP 8.3
            uses: shivammathur/setup-php@master
            with:
                php-version: 8.3
                extension: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml