name: ATMI-PlusMinus-Deploy

on:
  pull_request:
    branches:
      - main
  
  push:
    branches:
      - main
      - Laravel-CI/CD


jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
        -   uses: actions/checkout@v2

        -   name: Compile CSS and Javascript
            run: |
                npm install
                npm run build